import prisma from "@/libs/prismadb";
import { NextResponse } from "next/server";

export async function POST(request: Request) {
  const body = await request.json();

  const {
    firstname,
    lastname,
    email,
    phone,
    alternatePhone,
    gender,
    dateOfBirth,
    nextOfKin,
    nextOfKinPhone,
    state,
    lga,
    address,
    netMonthlyIncome,
    purposeOfLoan,
    desiredLoanAmount,
    customerPassport,
    guarantorName1,
    guarantorPhone1,
    guarantorPassport1,
    guarantorName2,
    guarantorPhone2,
    guarantorPassport2,
    customerIdentification,
    proofOfResidence,
    comments,
    businessName,
    businessType,
    businessPhone,
    businessAddress,
    businessEmail,
    cacNumber,
    country,
    cacDocument,
    websiteReg,
    maritalStatus,
    howYouHeard,
  } = body;
  const customer = await prisma.customer.create({
    data: {
      firstname,
      lastname,
      email,
      phone,
      alternatePhone,
      gender,
      dateOfBirth,
      nextOfKin,
      nextOfKinPhone,
      country,
      state,
      lga,
      address,
      netMonthlyIncome: parseFloat(netMonthlyIncome),
      purposeOfLoan,
      desiredLoanAmount: parseFloat(desiredLoanAmount),
      customerPassport,
      guarantorName1,
      guarantorPhone1,
      guarantorPassport1,
      guarantorName2,
      guarantorPhone2,
      guarantorPassport2,
      customerIdentification,
      proofOfResidence,
      comments,
      businessName,
      businessType,
      businessPhone,
      businessAddress,
      businessEmail,
      cacNumber,
      cacDocument,
      websiteReg,
      maritalStatus,
      howYouHeard,
    },
  });

  return NextResponse.json(customer);
}
